# Needed YAML tag for the configuration object
--- !<tag:barectf.org,2020/3/config>

# Configuration's trace
trace:
  # Type of the trace
  type:
    # Add standard field type aliases
    $include:
      - stdint.yaml
      - stdmisc.yaml

    # Native byte order is little-endian
    native-byte-order: little-endian

    # One clock type
    clock-types:
      # The Linux FS platform requires a clock type named `default`
      # which has a 1-GHz frequency and the `uint64_t` C type.
      default:
        frequency: 1000000000
        $c-type: uint64_t

    # One data stream type
    data-stream-types:
      # Stream type named `default`
      default:
        # Default data stream type
        $is-default: true

        # Default clock type: `default`
        $default-clock-type-name: default

        # Two event record types
        event-record-types:
          # Event record type named `one_integer`
          one_integer:
            payload-field-type:
              class: structure
              members:
                # One payload member: a 32-bit signed integer field type
                # (`int32_t` C type)
                - the_integer: int32

          # Event record type named `one_string`
          one_string:
            payload-field-type:
              class: structure
              members:
                # One payload member: a string field type
                # (`const char *` C type)
                - the_string: string