# Needed YAML tag for the configuration object
--- !<tag:barectf.org,2020/3/config>

# Configuration's trace
trace:
  environment:
    # create as a Linux system trace so we can use the utilities in trace compass
    hostname: "kd-client-b550-Asrock"
    domain: "kernel"
    sysname: "Linux"
    kernel_release: "5.11.0-41-generic"
    kernel_version: "#45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021"
    tracer_name: "lttng-modules"
    tracer_major: 2
    tracer_minor: 12
    tracer_patchlevel: 5
    trace_buffering_scheme: "global"
    trace_name: "kernel_trace_session"
    trace_creation_datetime: "20211202T214153-0800"
    product_uuid: "97c28570-2673-0000-0000-000000000000"

  type:
    uuid: 65cf7ac3-91e4-2e45-a796-584114633ec7
    $include:
      - stdint.yaml
      - stdmisc.yaml

    $field-type-aliases:
      comm_str:
        class: static-array
        length: 16
        element-field-type: byte-packed-uint8
      
      kernel_state:
        class: signed-enumeration
        size: 64
        mappings:
          TASK_RUNNING: [0]
          TASK_INTERRUPTIBLE: [1]
          TASK_UNINTERRUPTIBLE: [2]
          TASK_STOPPED: [4]
          TASK_TRACED: [8]
          EXIT_DEAD: [16]
          EXIT_ZOMBIE: [32]
          TASK_PARKED: [64]
          TASK_DEAD: [128]
          TASK_WAKEKILL: [256]
          TASK_WAKING: [512]
          TASK_NOLOAD: [1024]
          TASK_NEW: [2048]
          TASK_STATE_MAX: [4096]


    # Native byte order is little-endian
    native-byte-order: little-endian

    # One clock type
    clock-types:
      # The Linux FS platform requires a clock type named `default`
      # which has a 1-GHz frequency and the `uint64_t` C type.
      default:
        frequency: 1000000000
        $c-type: uint64_t

    # One data stream type
    data-stream-types:
      # Stream type named `default`
      default:
        $is-default: true

        $default-clock-type-name: default

        packet-context-field-type-extra-members:
          - cpu_id: uint32

        event-record-types:
          sched_switch:
            payload-field-type:
              class: structure
              members:
                - _prev_comm: string
                - _prev_tid: byte-packed-int32
                - _prev_prio: byte-packed-int32

                - _prev_state: kernel_state

                - _next_comm: string
                - _next_tid: byte-packed-int32
                - _next_prio: byte-packed-int32

          # # Event record type named `one_string`
          # one_string:
          #   payload-field-type:
          #     class: structure
          #     members:
          #       # One payload member: a string field type
          #       # (`const char *` C type)
          #       - the_string: string