FROM crops/poky:ubuntu-20.04
USER root

RUN apt-get update
RUN apt-get install xxd build-essential datamash gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm python3 tar -y

USER usersetup