# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure('2') do |config|
    config.vm.box = 'generic/ubuntu2004'

    MEMORY = 16384
    CPUS = 8

    config.vm.provider :libvirt do |libvirt|
        libvirt.driver = 'kvm'
        libvirt.cpu_mode = 'host-passthrough'
        libvirt.machine_virtual_size = 50

        libvirt.memory = MEMORY
        libvirt.cpus = CPUS
    end

    config.vm.provision 'shell', inline: 'apt update && apt full-upgrade -y'
    config.vm.provision 'shell', inline: 'apt install xxd build-essential datamash gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm python3 tar libtinfo5 -y'
end
