# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure('2') do |config|
    config.vm.box = 'generic/ubuntu2004'
    config.disksize.size = '200GB'

    MEMORY = 16384
    CPUS = 8

    unless Vagrant.has_plugin?("vagrant-disksize")
        raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
    end

    config.vm.provider :virtualbox do |v|
        v.memory = MEMORY
        v.cpus = CPUS
    end

    config.vm.synced_folder 'vagrant_mount', '/vagrant_mount'

    config.vm.provision 'shell', inline: '/vagrant_mount/Xilinx_Unified_2021.2_1021_0703/xsetup -c /vagrant_mount/install_config.txt --agree XilinxEULA,3rdPartyEULA,WebTalkTerms --batch Add'

    config.vm.provision 'shell', inline: 'apt update && apt full-upgrade -y'
    config.vm.provision 'shell', inline: 'apt install xxd build-essential datamash gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm python3 tar libtinfo5 -y'
end
