# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
vm_box = "ubuntu/focal64"
vm_ram = 16384
vm_cpus = 8
install_apt_pkg = 'apt update && apt full-upgrade -y && apt install xxd build-essential datamash gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm python3 tar libtinfo5 git-lfs -y'
Vagrant.configure('2') do |config|
    unless Vagrant.has_plugin?("vagrant-disksize")
        raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
    end

    config.vm.define "without_vitis" do |wv|
        wv.vm.box = vm_box
        wv.vm.hostname = 'without-vitis'
        wv.disksize.size = '70GB'

        wv.vm.synced_folder 'vagrant_mount', '/vagrant_mount'
        wv.vm.synced_folder 'scripts', '/scripts'

        wv.vm.provider :virtualbox do |v|
            v.memory = vm_ram
            v.cpus = vm_cpus
        end

        wv.vm.provision 'shell', inline: install_apt_pkg
    end

    config.vm.define "with_vitis" do |wv|
        wv.vm.box = vm_box
        wv.vm.hostname = 'with-vitis'
        wv.disksize.size = '250GB'

        wv.vm.synced_folder 'vagrant_mount', '/vagrant_mount'
        wv.vm.synced_folder 'scripts', '/scripts'

        wv.vm.provider :virtualbox do |v|
            v.memory = vm_ram
            v.cpus = vm_cpus
        end

        wv.vm.provision 'shell', inline: install_apt_pkg
        wv.vm.provision 'shell', inline: '/vagrant_mount/Xilinx_Unified_2021.2_1021_0703/xsetup -c /vagrant_mount/install_config.txt --agree XilinxEULA,3rdPartyEULA,WebTalkTerms --batch Add'
    end
end
