# Needed YAML tag for the configuration object
--- !<tag:barectf.org,2020/3/config>


trace:
  # NOTE: To be replaced by script
  $include: 
    - env_user.yml

  type:
    uuid: c61d3d36-7707-4619-95f5-dc4049b67573
    $include:
      - stdint.yaml
      - stdmisc.yaml

    $field-type-aliases:
      comm_str:
        class: static-array
        length: 16
        element-field-type: byte-packed-uint8
      
      kernel_state:
        class: signed-enumeration
        size: 64
        mappings:
          TASK_RUNNING: [0]
          TASK_INTERRUPTIBLE: [1]
          TASK_UNINTERRUPTIBLE: [2]
          TASK_STOPPED: [4]
          TASK_TRACED: [8]
          EXIT_DEAD: [16]
          EXIT_ZOMBIE: [32]
          TASK_PARKED: [64]
          TASK_DEAD: [128]
          TASK_WAKEKILL: [256]
          TASK_WAKING: [512]
          TASK_NOLOAD: [1024]
          TASK_NEW: [2048]
          TASK_STATE_MAX: [4096]
      
      user_stream_context:
        class: structure
        members:
          - _vpid: byte-packed-int32
          - _vtid: byte-packed-int32
          - _procname: string

      address_type:
        $inherit: byte-packed-uint64
        preferred-display-base: hex

    # Native byte order is little-endian
    native-byte-order: little-endian

    # One clock type
    clock-types:
      # The Linux FS platform requires a clock type named `default`
      # which has a 1-GHz frequency and the `uint64_t` C type.
      default:
        frequency: 1000000000
        $c-type: uint64_t

    # NOTE: The packet content and format is mostly copied from metadata file generated by lttng
    data-stream-types:
      kernel_stream:

        $default-clock-type-name: default

        packet-context-field-type-extra-members:
          - cpu_id: uint32

        event-record-types:
          sched_switch:
            payload-field-type:
              class: structure
              members:
                - _prev_comm: string
                - _prev_tid: byte-packed-int32
                - _prev_prio: byte-packed-int32

                - _prev_state: kernel_state

                - _next_comm: string
                - _next_tid: byte-packed-int32
                - _next_prio: byte-packed-int32
          sched_wakeup:
            payload-field-type:
              class: structure
              members:
                - _comm: string
                - _tid: byte-packed-int32
                - _prio: byte-packed-int32
                - _target_cpu: byte-packed-int32
          
          irq_handler_entry:
            payload-field-type:
              class: structure
              members:
                - _irq: byte-packed-int32
                - _name: string
          irq_handler_exit:
            payload-field-type:
              class: structure
              members:
                - _irq: byte-packed-int32
                - _ret: byte-packed-int32
          
          # NOTE: Faking tracing syscall can provide at least high level flamegraph

          # NOTE: This doesn't seem to show anything special, futex syscall is probably more useful
          # lock_acquired:
          #   payload-field-type:
          #     class: structure
          #     members:
          #       - _name: string
          #       - _lockdep_addr: address_type
          # lock_contended:
          #   payload-field-type:
          #     class: structure
          #     members:
          #       - _name: string
          #       - _lockdep_addr: address_type
          # lock_release:
          #   payload-field-type:
          #     class: structure
          #     members:
          #       - _name: string
          #       - _lockdep_addr: address_type
          # lock_acquire:
          #   payload-field-type:
          #     class: structure
          #     members:
          #       - _flags: byte-packed-uint32
          #       - _name: string
          #       - _lockdep_addr: address_type

          # NOTE: THIS DOESN'T SHOW ON TRACE COMPASS KERNEL MEMORY USAGE VIEW
          # IT ONLY SHOWS PAGE SIZE MM
          # leave this here for future reference
          # kmem_kmalloc:
          #   payload-field-type:
          #     class: structure
          #     members:
          #       - _call_site: address_type
          #       - _ptr: address_type
          #       - _bytes_req: byte-packed-uint64
          #       - _bytes_alloc: byte-packed-uint64
          #       - _gfp_flags: byte-packed-uint32
          # kmem_kfree:
          #   payload-field-type:
          #     class: structure
          #     members:
          #       - _call_site: address_type
          #       - _ptr: address_type

          # how lock flow works in the kernel
          # https://www.kernel.org/doc/html/latest/locking/lockstat.html

      user_stream:
        $default-clock-type-name: default

        packet-context-field-type-extra-members:
          - cpu_id: uint32
        
        event-record-common-context-field-type: user_stream_context

        event-record-types:
          lttng_ust_statedump_start:
            payload-field-type:
              class: structure
              members: []
          lttng_ust_statedump_procname:
            payload-field-type:
              class: structure
              members:
                - _procname: string
          lttng_ust_statedump_bin_info:
            payload-field-type:
              class: structure
              members:
                - _baddr: address_type
                - _memsz: byte-packed-uint64
                - _path: string
                - _is_pic: uint8
                - _has_build_id: uint8
                - _has_debug_link: uint8
          lttng_ust_statedump_end:
            payload-field-type:
              class: structure
              members: []

          lttng_ust_libc_calloc:
            payload-field-type:
              class: structure
              members:
                - _nmemb: byte-packed-uint64
                - _size: byte-packed-uint64
                - _ptr: address_type
          lttng_ust_libc_free:
            payload-field-type:
              class: structure
              members:
                - _ptr: address_type
          lttng_ust_libc_malloc:
            payload-field-type:
              class: structure
              members:
                - _size: byte-packed-uint64
                - _ptr: address_type
          lttng_ust_libc_realloc:
            payload-field-type:
              class: structure
              members:
                - _in_ptr: address_type
                - _size: byte-packed-uint64
                - _ptr: address_type
          lttng_ust_libc_memalign:
            payload-field-type:
              class: structure
              members:
                - _alignment: byte-packed-uint64
                - _size: byte-packed-uint64
                - _ptr: address_type
          lttng_ust_libc_posix_memalign:
            payload-field-type:
              class: structure
              members:
                - _out_ptr: address_type
                - _alignment: byte-packed-uint64
                - _size: byte-packed-uint64
                - _result: byte-packed-int32

          lttng_ust_cyg_profile_func_entry:
            payload-field-type:
              class: structure
              members:
                - _addr: address_type
                - _call_site: address_type
          lttng_ust_cyg_profile_func_exit:
            payload-field-type:
              class: structure
              members:
                - _addr: address_type
                - _call_site: address_type